# Exploratory Data Analysis

#### Importing Directory and Loading Data

In [2]:
import pandas as pd

fact_orders = pd.read_csv("../data/raw/fact_orders.csv")
fact_inventory = pd.read_csv("../data/raw/fact_inventory.csv")
dim_products = pd.read_csv("../data/raw/dim_products.csv")
dim_customers = pd.read_csv("../data/raw/dim_customers.csv")
dim_stores = pd.read_csv("../data/raw/dim_stores.csv")
dim_date = pd.read_csv("../data/raw/dim_date.csv")

##### Checking the Shape of the tables

In [3]:
tables = {
    "fact_orders": fact_orders,
    "fact_inventory": fact_inventory,
    "dim_products": dim_products,
    "dim_customers": dim_customers,
    "dim_stores": dim_stores,
    "dim_date": dim_date
}

for name, table in tables.items():
    print(f"{name}: {table.shape}")

fact_orders: (20001, 12)
fact_inventory: (4999, 8)
dim_products: (250, 7)
dim_customers: (2501, 6)
dim_stores: (15, 6)
dim_date: (731, 7)

##### Checking the available colums in the tables

In [5]:
fact_orders.head(2)

,order_id,order_date,order_time,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,sales_amount,payment_method
0,ORD000001,2025-09-01,16:25:00,CUST02281,PROD0100,STR009,Online,4,35910.88,15,122096.99,Card
1,ORD000002,2025-08-23,11:04:00,CUST01960,PROD0070,STR002,Offline,5,15345.24,0,76726.20,UPI

In [6]:
fact_inventory.head(2)

,inventory_id,product_id,store_id,stock_received,stock_sold,current_stock,reorder_level,inventory_date
0,INV00001,PROD0016,STR010,280,4,301,22.0,2024-07-04
1,INV00002,PROD0090,STR009,59,112,310,52.0,2024-08-11

In [7]:
dim_products.head(2)

,product_id,product_name,category,sub_category,brand,cost_price,selling_price
0,PROD0001,Prestige Furniture 1,Home & Kitchen,Furniture,Prestige,23858.26,35154.87
1,PROD0002,Dell Mobiles 2,Electronics,Mobiles,Dell,21238.80,44634.91

In [8]:
dim_customers.head(2)

  customer_id customer_name    city        state loyalty_status signup_date
0   CUST00001   Priya Gupta  Mumbai  Maharashtra         Silver  2022-05-24
1   CUST00002   Aarav Verma   Patna        Bihar        Regular  2021-11-08

In [9]:
dim_stores.head(2)

  store_id         store_name    city        state region  store_type
0   STR001   Delhi Retail Hub   Delhi        Delhi  North  Standalone
1   STR002  Mumbai Retail Hub  Mumbai  Maharashtra   West        Mall

In [10]:
dim_date.head(2)

    full_date  year quarter    month  month_number day_name is_weekend
0  2024-01-01  2024      Q1  January             1   Monday         No
1  2024-01-02  2024      Q1  January             1  Tuesday         No

##### Checking the missing values

In [13]:
#Missing Values
fact_orders.isnull().sum()

order_id          0
order_date        0
order_time        0
customer_id       0
product_id        0
store_id          0
sales_channel     0
quantity          0
unit_price        1
discount_pct      0
sales_amount      0
payment_method    0
dtype: int64

In [14]:
#Missing Values
fact_inventory.isnull().sum()

inventory_id      0
product_id        0
store_id          0
stock_received    0
stock_sold        0
current_stock     0
reorder_level     1
inventory_date    0
dtype: int64

In [15]:
#Missing Values
dim_products.isnull().sum()

product_id       0
product_name     1
category         0
sub_category     0
brand            0
cost_price       0
selling_price    1
dtype: int64

In [16]:
#Missing Values
dim_customers.isnull().sum()

customer_id       0
customer_name     1
city              0
state             0
loyalty_status    0
signup_date       0
dtype: int64

In [17]:
#Missing Values
dim_stores.isnull().sum()

store_id      0
store_name    0
city          0
state         1
region        0
store_type    0
dtype: int64

In [18]:
#Missing Values
dim_date.isnull().sum()

full_date       0
year            0
quarter         0
month           0
month_number    0
day_name        0
is_weekend      0
dtype: int64